# Generated by Django 4.2.20 on 2025-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='azure_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
